[package]
name = "token-launch-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tool for the Solana Launchpad program"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
# Local dependencies
token-launch = { path = "../program" }

# Solana dependencies
solana-program = { workspace = true }
spl-token = { workspace = true }

# Serialization and CLI
borsh = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }

# Error handling
thiserror = { workspace = true }