[package]
name = "token-launch-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tool for the Solana Launchpad program"

[[bin]]
name = "cli"
path = "src/main.rs"

[build]
target-dir = "target-cli"

[dependencies]
# Local dependencies
token-launch = { path = "../program" }

clap = { version = "4.0", features = ["derive"] }
solana-program = { workspace = true }
solana-program-test = "1.18.11"
solana-sdk = "1.18.11"
solana-client = "1.18.11"
borsh = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
getrandom = { workspace = true }